# Define the system of units to use internally.
InternalUnitSystem:
  UnitMass_in_cgs:     1   # Grams
  UnitLength_in_cgs:   1   # Centimeters
  UnitVelocity_in_cgs: 1   # Centimeters per second
  UnitCurrent_in_cgs:  1   # Amperes
  UnitTemp_in_cgs:     1   # Kelvin

# Parameters governing the time integration
TimeIntegration:
  time_begin: 0.0   # The starting time of the simulation (in internal units).
  time_end:   10.4   # The end time of the simulation (in internal units).
  dt_min:     1e-6  # The minimal time-step size of the simulation (in internal units).
  dt_max:     1e-2  # The maximal time-step size of the simulation (in internal units).

# Parameters governing the snapshots
Snapshots:
  basename:            kelvin_helmholtz_3d  # Common part of the name of output files
  output_list_on:      1
  output_list:         ./output_list.txt

# Parameters governing the conserved quantities statistics
Statistics:
  delta_time:          1. # Time between statistics output

# Parameters for the hydrodynamics scheme
SPH:
  resolution_eta:        1.2348   # Target smoothing length in units of the mean inter-particle separation (1.2348 == 48Ngbs with the cubic spline kernel).
  CFL_condition:         0.1      # Courant-Friedrich-Levy condition for time integration.

# Parameters related to the initial conditions
InitialConditions:
  file_name:  ../kelvin_helmholtz_3d.hdf5
  periodic:   1
  replicate:  NTILES

Scheduler:
  max_top_level_cells:    MAX_TOP_CELLS